'use client';
import {useState,useRef,useEffect,useId} from 'react';
import {motion,AnimatePresence,LayoutGroup,useReducedMotion,useIsPresent} from 'motion/react';
import {Volume2,VolumeX,Play} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
const stages=['conversation','memory','recall'];
const labels=['Conversation','Memory','Recall'];
const spring={type:'spring' as const,stiffness:100,damping:18,mass:.7};
function Word({id,children,className=''}:{id:string;children:React.ReactNode;className?:string}){const reduce=useReducedMotion();return <motion.span layoutId={reduce?undefined:id} transition={reduce?{duration:0}:spring} className={'memory-word '+className}>{children}</motion.span>}
function Stage({step}:{step:string}){
 const reduce=useReducedMotion();const present=useIsPresent();
 return <motion.div className={'memory-panel animated-memory-panel '+(step==='memory'?'graph-panel':'')} aria-hidden={!present} initial={reduce?false:{opacity:0,y:25,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={reduce?{opacity:0}:{opacity:0,y:-20,scale:1.025}} transition={{duration:reduce?0:.55,ease:[.16,1,.3,1]}}>
 {step==='conversation'&&<><span className="eyebrow">01 — BE IN THE CONVERSATION</span><div className="waveform" aria-hidden="true">{Array.from({length:48},(_,i)=><i key={i} style={{height:`${Math.round(12+Math.abs(Math.sin(i*.7))*32+Math.abs(Math.cos(i*.3))*22)}px`,animationDelay:`${(i*-.11).toFixed(2)}s`}}/>)}</div><blockquote>“I’m <Word id="ada">Ada</Word>. We’re building <Word id="company">NuLedger</Word>.<br/>Raising a <Word id="seed">seed round</Word>.<br/>Looking for <Word id="topic">fintech</Word> <Word id="followup">introductions</Word>.”</blockquote><span className="demo-hint">The conversation happens. Context starts taking shape.</span></>}
 {step==='memory'&&<><span className="eyebrow">02 — CONNECT THE CONTEXT</span><div className="memory-constellation"><svg className="constellation-edges" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true">{[[220,180],[780,180],[780,780],[220,780]].map(([x,y],i)=><g key={i}><motion.path d={`M500 450 Q${x} 450 ${x} ${y}`} fill="none" stroke="#6988ff" strokeWidth="2" vectorEffect="non-scaling-stroke" initial={{pathLength:0,opacity:0}} animate={{pathLength:1,opacity:.75}} transition={{duration:reduce?0:.8,delay:reduce?0:i*.12}}/><motion.circle r="6" fill="#b5c7ff" initial={{cx:500,cy:450,opacity:0}} animate={{cx:x,cy:y,opacity:[0,1,0]}} transition={{duration:reduce?0:1,delay:reduce?0:.2+i*.14}}/></g>)}</svg>{[{id:'ada',label:'Ada',kind:'PERSON',x:50,y:45},{id:'company',label:'NuLedger',kind:'COMPANY',x:22,y:18},{id:'seed',label:'seed round',kind:'INTENT',x:78,y:18},{id:'topic',label:'fintech',kind:'TOPIC',x:78,y:78},{id:'followup',label:'introductions',kind:'FOLLOW-UP',x:22,y:78}].map((n,i)=><motion.div key={n.id} className={'constellation-node '+(i===0?'core-node':'')} style={{left:n.x+'%',top:n.y+'%'}} initial={reduce?false:{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{...spring,delay:reduce?0:.05*i}}><span className="constellation-kind">{n.kind}</span><Word id={n.id}>{n.label}</Word></motion.div>)}</div><span className="demo-hint">People, companies, intent, and follow-ups. Connected.</span></>}
 {step==='recall'&&<><span className="eyebrow">03 — PICK UP WHERE YOU LEFT OFF</span><motion.div layout className="recall-card" initial={reduce?false:{rotateY:18,rotateX:6}} animate={{rotateY:0,rotateX:0}} transition={spring}><div className="recall-avatar">A</div><div><span className="card-micro">CONTEXT RECOVERED</span><h4><Word id="ada">Ada</Word></h4><p>Founder, <Word id="company">NuLedger</Word></p></div><div className="recall-facts"><span>BUILDING <b><Word id="topic">fintech</Word></b></span><span>LOOKING FOR <b>A <Word id="seed">seed round</Word></b></span><span>YOUR FOLLOW-UP <b>Send the <Word id="followup">introductions</Word> you promised.</b></span></div></motion.div><span className="demo-hint">The useful detail, back when you need it.</span></>}
 </motion.div>;
}
export function MemoryDemo(){
 const [step,setStep]=useState('conversation');const [sound,setSound]=useState(false);const [playing,setPlaying]=useState(false);const audio=useRef<HTMLAudioElement|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const id=useId().replace(/:/g,'');
 const playSound=()=>{if(!audio.current)audio.current=new Audio('/memory-chime.mp3');audio.current.volume=.18;audio.current.currentTime=0;void audio.current.play().catch(()=>{});};
 const change=(s:string)=>{if(timer.current)clearTimeout(timer.current);setPlaying(false);setStep(s);if(sound)playSound();};
 useEffect(()=>()=>{audio.current?.pause();if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{if(!playing)return;timer.current=setTimeout(()=>{const next=stages.indexOf(step)+1;if(next>=stages.length){setPlaying(false);return;}setStep(stages[next]);if(sound)playSound();},2000);return()=>{if(timer.current)clearTimeout(timer.current);};},[step,playing,sound]);
 return <LayoutGroup id={id}><div className="memory-demo"><div className="demo-top"><span><i/> RECALL / MEMORY ENGINE</span><button className="play-sequence" onClick={()=>{if(timer.current)clearTimeout(timer.current);if(playing){setPlaying(false);}else{setStep('conversation');setPlaying(true);if(sound)playSound();}}}>{playing?<><span className="pause-symbol"/>Pause</>:<><Play size={12}/>Play the sequence</>}</button></div><Tabs value={step} onValueChange={change} className="memory-tabs"><div className="memory-stage" role="tabpanel" id={id+'-panel'} aria-labelledby={id+'-'+step}><AnimatePresence initial={false}><Stage key={step} step={step}/></AnimatePresence></div><TabsList className="memory-controls" aria-label="Explore Recall">{stages.map((s,i)=><TabsTrigger id={id+'-'+s} aria-controls={id+'-panel'} value={s} key={s}><span>0{i+1}</span>{labels[i]}</TabsTrigger>)}</TabsList></Tabs><div className="demo-bottom"><span>SAMPLE DATA · RECONSTRUCTED INTERFACE</span><button className="sound-toggle" aria-pressed={sound} onClick={()=>{setSound(!sound);if(!sound)playSound();else audio.current?.pause();}}>{sound?<Volume2 size={14}/>:<VolumeX size={14}/>}Sound {sound?'on':'off'}</button></div></div></LayoutGroup>;
}
